spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.css,*.ico,/druid/*"

      aop-patterns: com.ludens.webadmin.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8888

  redis:
    host: 47.100.209.251
    port: 6379
    password: 123456

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
      enabled: true

    metrics:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true